#cloud-config
hostname: host3-r-mgmt
EXTRA_CMDLINE: /init
rancher:
  console: ubuntu
  environment:
    EXTRA_CMDLINE: /init
  network:
    dns:
      nameservers:
      - 8.8.8.8
    interfaces:
      eth0:
        address: 10.17.67.151/24
        dhcp: false
        gateway: 10.17.67.1
        mtu: 1500
ssh_authorized_keys:
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIxWKOZwVUnePMPwnzfJv4TOE+LrFRiC6bE0B6y2mQ6gBEQws80l3eIJ1VsAsrdP025gAYczHqirgrWkZlG5ev0LnmIEsXNogitk00wsp80LUGhZYTgYICRfJIrESvFU04CK7QW3+xh25JChGrLrR/XWI9ht3wQ5k9mAm10Gz+F9wBHV1iAl2sxLYP9KTGaqiSf0T1FSKX5gCnAVgGphQ1hYDLShw1ZuzbDHZgaHqaE7Rs3JthhrFDPVkZFiOM+w/AMjqLsqdFUGyj1ixnHg0NfT/b4g0ZmQrjE0uf4E+4RasoRdZOKYKbJLEXwpUYvq8CiSLD3xqtXrtjXIXIHZ4h jester@PortoPlozo
- ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6ZYtFM16YIJ9XfcxtslkRsLGrW7LMFE2Dd+HyvnhGSp5IJfcu75aeulmZuB8j8xLs4qhP8970rFquG7sjz7/EaVsh0qEMCr3CwuN9PvyXNIaC1QIqsg56ZlzX4/E7A1kizcKAJgXxsMcNmYPV5gMEaFhumI9WVg3pGml2wV0NvgwU96GPmCfRSToxz0S0bg6VD1mJdaUlbsQmXFbvLW6g69tvJ0mVCxLRLvFBj/DPSV6ft06m+80TwrafjmWhWPzOCxhLBymMU+EK8WhDlXnD615MhFw2HxJi/UDdJLEYH0X9haQWDUgvxQszNeWdCDuJas4kE5VAMv+Q1XBCtx2V root@CAM-CZANGERLE
